on: push

defaults:
  run:
    shell: bash

jobs:
  test:
    if: "!contains('refs/heads/main refs/heads/staging', github.ref)"
    runs-on: ubuntu-20.04
    steps:
      - name: Set up golang env
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16"

      - name: Checkout
        uses: actions/checkout@v2

      # - name: Lint if any
      #   run: echo Lint

      - name: Test
        run: go test -v ./...

　export-env:
    if: contains('refs/heads/staging refs/heads/main refs/heads/test1', github.ref)
    runs-on: ubuntu-20.04


  build-deploy:
    if: contains('refs/heads/staging refs/heads/main refs/heads/test1', github.ref) && ${{ success() }}
    needs: test
    runs-on: ubuntu-20.04
    env:
      FOO: BAR
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: print env1
        run: |
          echo ${FOO}

      - name: print env2
        run: |
          echo ${FOO}


    # - name: Cache go.sum
      #   id: cache-go-sum
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/go/pkg/mod
      #     key: ${{ runner.os }}-go-v1-${{ hashFiles('**/go.sum') }}
      #     restore-keys: ${{ runner.os }}-go-

      # - name: Cache result
      #   run: echo ${{ steps.cache-go-sum.outputs.cache-hit }}

      # - run: echo "Jobs done with ${{ job.status }}."
