name: GitHub Actions Demo
on: [push]
jobs:
  aws-iam:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run: |
          echo "${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - run: echo "🍏 This job's status is ${{ job.status }}."
