name: GitHub Actions Demo
on: [push]
jobs:
  aws-iam:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-external-id: ${{ secrests.AWS_ROLE_EXTERNAL_ID }}
          role-duration-seconds: 60
          role-session-name: some session

      - name: test aws cli
        run: |
          aws s3 ls
