on:
  push:
    branches:
      - dev0
      - !staging
      - !main

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Golang env
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16'

    - name: print go version
      run: go version

    - name: go test
      run: go test
