on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16'
    - name: pring go version
      run: go version

    - name: go test
      run: go test
